import { useState } from 'react';
import { StyleSheet, FlatList, Image, Platform, Pressable } from 'react-native';

export default function EmojiList({ onSelect, onCloseModal }: { onSelect: any, onCloseModal: any }) {
    const [emoji] = useState([
        require("../assets/emojis/emoji-png-0001.png"),
        require("../assets/emojis/emoji-png-0002.png"),
        require("../assets/emojis/emoji-png-0003.png"),
        require("../assets/emojis/emoji-png-0004.png"),
        require("../assets/emojis/emoji-png-0005.png"),
        require("../assets/emojis/emoji-png-0006.png"),
        require("../assets/emojis/emoji-png-0007.png"),
        require("../assets/emojis/emoji-png-0008.png"),
        require("../assets/emojis/emoji-png-0009.png"),
        require("../assets/emojis/emoji-png-0010.png"),
        require("../assets/emojis/emoji-png-0011.png"),
        require("../assets/emojis/emoji-png-0012.png"),
        require("../assets/emojis/emoji-png-0013.png"),
        require("../assets/emojis/emoji-png-0014.png"),
        require("../assets/emojis/emoji-png-0015.png"),
        require("../assets/emojis/emoji-png-0016.png"),
        require("../assets/emojis/emoji-png-0017.png"),
        require("../assets/emojis/emoji-png-0018.png"),
        require("../assets/emojis/emoji-png-0019.png"),
        require("../assets/emojis/emoji-png-0020.png"),
        require("../assets/emojis/emoji-png-0021.png"),
        require("../assets/emojis/emoji-png-0022.png"),
        require("../assets/emojis/emoji-png-0023.png"),
        require("../assets/emojis/emoji-png-0024.png"),
        require("../assets/emojis/emoji-png-0025.png"),
        require("../assets/emojis/emoji-png-0026.png"),
        require("../assets/emojis/emoji-png-0027.png"),
        require("../assets/emojis/emoji-png-0028.png"),
        require("../assets/emojis/emoji-png-0029.png"),
        require("../assets/emojis/emoji-png-0030.png"),
        require("../assets/emojis/emoji-png-0031.png"),
        require("../assets/emojis/emoji-png-0032.png"),
        require("../assets/emojis/emoji-png-0033.png"),
        require("../assets/emojis/emoji-png-0034.png"),
        require("../assets/emojis/emoji-png-0035.png"),
        require("../assets/emojis/emoji-png-0037.png"),
        require("../assets/emojis/emoji-png-0038.png"),
        require("../assets/emojis/emoji-png-0039.png"),
        require("../assets/emojis/emoji-png-0040.png"),
        require("../assets/emojis/emoji-png-0041.png"),
        require("../assets/emojis/emoji-png-0042.png"),
        require("../assets/emojis/emoji-png-0043.png"),
        require("../assets/emojis/emoji-png-0044.png"),
        require("../assets/emojis/emoji-png-0045.png"),
        require("../assets/emojis/emoji-png-0046.png"),
        require("../assets/emojis/emoji-png-0047.png"),
        require("../assets/emojis/emoji-png-0048.png"),
        require("../assets/emojis/emoji-png-0049.png"),
        require("../assets/emojis/emoji-png-0050.png"),
        require("../assets/emojis/emoji-png-0051.png"),
        require("../assets/emojis/emoji-png-0052.png"),
        require("../assets/emojis/emoji-png-0053.png"),
        require("../assets/emojis/emoji-png-0054.png"),
        require("../assets/emojis/emoji-png-0055.png"),
        require("../assets/emojis/emoji-png-0056.png"),
        require("../assets/emojis/emoji-png-0057.png"),
        require("../assets/emojis/emoji-png-0058.png"),
        require("../assets/emojis/emoji-png-0059.png"),
        require("../assets/emojis/emoji-png-0060.png"),
        require("../assets/emojis/emoji-png-0061.png"),
        require("../assets/emojis/emoji-png-0062.png"),
        require("../assets/emojis/emoji-png-0063.png"),
        require("../assets/emojis/emoji-png-0064.png"),
        require("../assets/emojis/emoji-png-0065.png"),
        require("../assets/emojis/emoji-png-0066.png"),
        require("../assets/emojis/emoji-png-0067.png"),
        require("../assets/emojis/emoji-png-0068.png"),
        require("../assets/emojis/emoji-png-0069.png"),
        require("../assets/emojis/emoji-png-0070.png"),
        require("../assets/emojis/emoji-png-0071.png"),
        require("../assets/emojis/emoji-png-0072.png"),
        require("../assets/emojis/emoji-png-0073.png"),
        require("../assets/emojis/emoji-png-0074.png"),
        require("../assets/emojis/emoji-png-0075.png"),
        require("../assets/emojis/emoji-png-0076.png"),
        require("../assets/emojis/emoji-png-0077.png"),
        require("../assets/emojis/emoji-png-0078.png"),
        require("../assets/emojis/emoji-png-0079.png"),
        require("../assets/emojis/emoji-png-0080.png"),
        require("../assets/emojis/emoji-png-0081.png"),
        require("../assets/emojis/emoji-png-0082.png"),
        require("../assets/emojis/emoji-png-0083.png"),
        require("../assets/emojis/emoji-png-0084.png"),
        require("../assets/emojis/emoji-png-0085.png"),
        require("../assets/emojis/emoji-png-0086.png"),
        require("../assets/emojis/emoji-png-0087.png"),
        require("../assets/emojis/emoji-png-0088.png"),
        require("../assets/emojis/emoji-png-0089.png"),
        require("../assets/emojis/emoji-png-0090.png"),
        require("../assets/emojis/emoji-png-0091.png"),
        require("../assets/emojis/emoji-png-0092.png"),
        require("../assets/emojis/emoji-png-0093.png"),
        require("../assets/emojis/emoji-png-0094.png"),
        require("../assets/emojis/emoji-png-0095.png"),
        require("../assets/emojis/emoji-png-0096.png"),
        require("../assets/emojis/emoji-png-0097.png"),
        require("../assets/emojis/emoji-png-0098.png"),
        require("../assets/emojis/emoji-png-0099.png"),
        require("../assets/emojis/emoji-png-0100.png"),
        require("../assets/emojis/emoji-png-0101.png"),
        require("../assets/emojis/emoji-png-0102.png"),
        require("../assets/emojis/emoji-png-0103.png"),
        require("../assets/emojis/emoji-png-0104.png"),
        require("../assets/emojis/emoji-png-0105.png"),
        require("../assets/emojis/emoji-png-0106.png"),
        require("../assets/emojis/emoji-png-0107.png"),
        require("../assets/emojis/emoji-png-0108.png"),
        require("../assets/emojis/emoji-png-0109.png"),
        require("../assets/emojis/emoji-png-0110.png"),
        require("../assets/emojis/emoji-png-0111.png"),
        require("../assets/emojis/emoji-png-0112.png"),
        require("../assets/emojis/emoji-png-0113.png"),
        require("../assets/emojis/emoji-png-0114.png"),
        require("../assets/emojis/emoji-png-0115.png"),
        require("../assets/emojis/emoji-png-0116.png"),
        require("../assets/emojis/emoji-png-0117.png"),
        require("../assets/emojis/emoji-png-0118.png"),
        require("../assets/emojis/emoji-png-0119.png"),
        require("../assets/emojis/emoji-png-0120.png"),
        require("../assets/emojis/emoji-png-0121.png"),
        require("../assets/emojis/emoji-png-0122.png"),
        require("../assets/emojis/emoji-png-0123.png"),
        require("../assets/emojis/emoji-png-0124.png"),
        require("../assets/emojis/emoji-png-0125.png"),
        require("../assets/emojis/emoji-png-0126.png"),
        require("../assets/emojis/emoji-png-0141.png"),
        require("../assets/emojis/emoji-png-0150.png"),
        require("../assets/emojis/emoji-png-0151.png"),
        require("../assets/emojis/emoji-png-0152.png"),
        require("../assets/emojis/emoji-png-0153.png"),
        require("../assets/emojis/emoji-png-0154.png"),
        require("../assets/emojis/emoji-png-0155.png"),
        require("../assets/emojis/emoji-png-0156.png"),
        require("../assets/emojis/emoji-png-0157.png"),
    ]);

    return (
        <FlatList
            horizontal
            showsHorizontalScrollIndicator={Platform.OS === 'web'}
            data={emoji}
            contentContainerStyle={styles.listContainer}
            renderItem={({ item, index }) => (
                <Pressable
                    onPress={() => {
                        onSelect(item);
                        onCloseModal();
                    }}>
                    <Image source={item} key={index} style={styles.image} />
                </Pressable>
            )}
        />
    );
}

const styles = StyleSheet.create({
    listContainer: {
        borderTopRightRadius: 10,
        borderTopLeftRadius: 10,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    image: {
        width: 100,
        height: 100,
        marginRight: 20,
    },
});
